//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("StocksHistoricalDataModel", "FK_option_bids_options", "s_options", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(zHFT.StrategyHandler.SecurityListSaver.DataAccess.s_options), "s_option_bids", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(zHFT.StrategyHandler.SecurityListSaver.DataAccess.s_option_bids), true)]
[assembly: EdmRelationshipAttribute("StocksHistoricalDataModel", "FK_option_closing_prices_options", "s_options", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(zHFT.StrategyHandler.SecurityListSaver.DataAccess.s_options), "s_option_closing_prices", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(zHFT.StrategyHandler.SecurityListSaver.DataAccess.s_option_closing_prices), true)]

#endregion

namespace zHFT.StrategyHandler.SecurityListSaver.DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StocksHistoricalDataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StocksHistoricalDataEntities object using the connection string found in the 'StocksHistoricalDataEntities' section of the application configuration file.
        /// </summary>
        public StocksHistoricalDataEntities() : base("name=StocksHistoricalDataEntities", "StocksHistoricalDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StocksHistoricalDataEntities object.
        /// </summary>
        public StocksHistoricalDataEntities(string connectionString) : base(connectionString, "StocksHistoricalDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StocksHistoricalDataEntities object.
        /// </summary>
        public StocksHistoricalDataEntities(EntityConnection connection) : base(connection, "StocksHistoricalDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<stocks_prices> stocks_prices
        {
            get
            {
                if ((_stocks_prices == null))
                {
                    _stocks_prices = base.CreateObjectSet<stocks_prices>("stocks_prices");
                }
                return _stocks_prices;
            }
        }
        private ObjectSet<stocks_prices> _stocks_prices;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<categories> categories
        {
            get
            {
                if ((_categories == null))
                {
                    _categories = base.CreateObjectSet<categories>("categories");
                }
                return _categories;
            }
        }
        private ObjectSet<categories> _categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<countries> countries
        {
            get
            {
                if ((_countries == null))
                {
                    _countries = base.CreateObjectSet<countries>("countries");
                }
                return _countries;
            }
        }
        private ObjectSet<countries> _countries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<markets> markets
        {
            get
            {
                if ((_markets == null))
                {
                    _markets = base.CreateObjectSet<markets>("markets");
                }
                return _markets;
            }
        }
        private ObjectSet<markets> _markets;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<s_options> s_options
        {
            get
            {
                if ((_s_options == null))
                {
                    _s_options = base.CreateObjectSet<s_options>("s_options");
                }
                return _s_options;
            }
        }
        private ObjectSet<s_options> _s_options;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<s_option_bids> s_option_bids
        {
            get
            {
                if ((_s_option_bids == null))
                {
                    _s_option_bids = base.CreateObjectSet<s_option_bids>("s_option_bids");
                }
                return _s_option_bids;
            }
        }
        private ObjectSet<s_option_bids> _s_option_bids;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<s_option_closing_prices> s_option_closing_prices
        {
            get
            {
                if ((_s_option_closing_prices == null))
                {
                    _s_option_closing_prices = base.CreateObjectSet<s_option_closing_prices>("s_option_closing_prices");
                }
                return _s_option_closing_prices;
            }
        }
        private ObjectSet<s_option_closing_prices> _s_option_closing_prices;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<s_stocks> s_stocks
        {
            get
            {
                if ((_s_stocks == null))
                {
                    _s_stocks = base.CreateObjectSet<s_stocks>("s_stocks");
                }
                return _s_stocks;
            }
        }
        private ObjectSet<s_stocks> _s_stocks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<stocks_market_data> stocks_market_data
        {
            get
            {
                if ((_stocks_market_data == null))
                {
                    _stocks_market_data = base.CreateObjectSet<stocks_market_data>("stocks_market_data");
                }
                return _stocks_market_data;
            }
        }
        private ObjectSet<stocks_market_data> _stocks_market_data;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the stocks_prices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostocks_prices(stocks_prices stocks_prices)
        {
            base.AddObject("stocks_prices", stocks_prices);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocategories(categories categories)
        {
            base.AddObject("categories", categories);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the countries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocountries(countries countries)
        {
            base.AddObject("countries", countries);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the markets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomarkets(markets markets)
        {
            base.AddObject("markets", markets);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the s_options EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTos_options(s_options s_options)
        {
            base.AddObject("s_options", s_options);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the s_option_bids EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTos_option_bids(s_option_bids s_option_bids)
        {
            base.AddObject("s_option_bids", s_option_bids);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the s_option_closing_prices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTos_option_closing_prices(s_option_closing_prices s_option_closing_prices)
        {
            base.AddObject("s_option_closing_prices", s_option_closing_prices);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the s_stocks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTos_stocks(s_stocks s_stocks)
        {
            base.AddObject("s_stocks", s_stocks);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the stocks_market_data EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostocks_market_data(stocks_market_data stocks_market_data)
        {
            base.AddObject("stocks_market_data", stocks_market_data);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StocksHistoricalDataModel", Name="categories")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class categories : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new categories object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static categories Createcategories(global::System.Int32 id, global::System.String name)
        {
            categories categories = new categories();
            categories.id = id;
            categories.name = name;
            return categories;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StocksHistoricalDataModel", Name="countries")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class countries : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new countries object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="code">Initial value of the code property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static countries Createcountries(global::System.Int32 id, global::System.String code, global::System.String name)
        {
            countries countries = new countries();
            countries.id = id;
            countries.code = code;
            countries.name = name;
            return countries;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String code
        {
            get
            {
                return _code;
            }
            set
            {
                OncodeChanging(value);
                ReportPropertyChanging("code");
                _code = StructuralObject.SetValidValue(value, false, "code");
                ReportPropertyChanged("code");
                OncodeChanged();
            }
        }
        private global::System.String _code;
        partial void OncodeChanging(global::System.String value);
        partial void OncodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StocksHistoricalDataModel", Name="markets")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class markets : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new markets object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="code">Initial value of the code property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="country">Initial value of the country property.</param>
        public static markets Createmarkets(global::System.Int32 id, global::System.String code, global::System.String name, global::System.String country)
        {
            markets markets = new markets();
            markets.id = id;
            markets.code = code;
            markets.name = name;
            markets.country = country;
            return markets;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String code
        {
            get
            {
                return _code;
            }
            set
            {
                OncodeChanging(value);
                ReportPropertyChanging("code");
                _code = StructuralObject.SetValidValue(value, false, "code");
                ReportPropertyChanged("code");
                OncodeChanged();
            }
        }
        private global::System.String _code;
        partial void OncodeChanging(global::System.String value);
        partial void OncodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String country
        {
            get
            {
                return _country;
            }
            set
            {
                OncountryChanging(value);
                ReportPropertyChanging("country");
                _country = StructuralObject.SetValidValue(value, false, "country");
                ReportPropertyChanged("country");
                OncountryChanged();
            }
        }
        private global::System.String _country;
        partial void OncountryChanging(global::System.String value);
        partial void OncountryChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StocksHistoricalDataModel", Name="s_option_bids")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class s_option_bids : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new s_option_bids object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="symbol">Initial value of the symbol property.</param>
        /// <param name="timestamp">Initial value of the timestamp property.</param>
        /// <param name="size">Initial value of the size property.</param>
        /// <param name="price">Initial value of the price property.</param>
        /// <param name="side">Initial value of the side property.</param>
        /// <param name="option_id">Initial value of the option_id property.</param>
        public static s_option_bids Creates_option_bids(global::System.Int64 id, global::System.String symbol, global::System.DateTime timestamp, global::System.Int32 size, global::System.Decimal price, global::System.String side, global::System.Int64 option_id)
        {
            s_option_bids s_option_bids = new s_option_bids();
            s_option_bids.id = id;
            s_option_bids.symbol = symbol;
            s_option_bids.timestamp = timestamp;
            s_option_bids.size = size;
            s_option_bids.price = price;
            s_option_bids.side = side;
            s_option_bids.option_id = option_id;
            return s_option_bids;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String symbol
        {
            get
            {
                return _symbol;
            }
            set
            {
                OnsymbolChanging(value);
                ReportPropertyChanging("symbol");
                _symbol = StructuralObject.SetValidValue(value, false, "symbol");
                ReportPropertyChanged("symbol");
                OnsymbolChanged();
            }
        }
        private global::System.String _symbol;
        partial void OnsymbolChanging(global::System.String value);
        partial void OnsymbolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime timestamp
        {
            get
            {
                return _timestamp;
            }
            set
            {
                OntimestampChanging(value);
                ReportPropertyChanging("timestamp");
                _timestamp = StructuralObject.SetValidValue(value, "timestamp");
                ReportPropertyChanged("timestamp");
                OntimestampChanged();
            }
        }
        private global::System.DateTime _timestamp;
        partial void OntimestampChanging(global::System.DateTime value);
        partial void OntimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 size
        {
            get
            {
                return _size;
            }
            set
            {
                OnsizeChanging(value);
                ReportPropertyChanging("size");
                _size = StructuralObject.SetValidValue(value, "size");
                ReportPropertyChanged("size");
                OnsizeChanged();
            }
        }
        private global::System.Int32 _size;
        partial void OnsizeChanging(global::System.Int32 value);
        partial void OnsizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value, "price");
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Decimal _price;
        partial void OnpriceChanging(global::System.Decimal value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String side
        {
            get
            {
                return _side;
            }
            set
            {
                OnsideChanging(value);
                ReportPropertyChanging("side");
                _side = StructuralObject.SetValidValue(value, false, "side");
                ReportPropertyChanged("side");
                OnsideChanged();
            }
        }
        private global::System.String _side;
        partial void OnsideChanging(global::System.String value);
        partial void OnsideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> underlying_price
        {
            get
            {
                return _underlying_price;
            }
            set
            {
                Onunderlying_priceChanging(value);
                ReportPropertyChanging("underlying_price");
                _underlying_price = StructuralObject.SetValidValue(value, "underlying_price");
                ReportPropertyChanged("underlying_price");
                Onunderlying_priceChanged();
            }
        }
        private Nullable<global::System.Decimal> _underlying_price;
        partial void Onunderlying_priceChanging(Nullable<global::System.Decimal> value);
        partial void Onunderlying_priceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 option_id
        {
            get
            {
                return _option_id;
            }
            set
            {
                Onoption_idChanging(value);
                ReportPropertyChanging("option_id");
                _option_id = StructuralObject.SetValidValue(value, "option_id");
                ReportPropertyChanged("option_id");
                Onoption_idChanged();
            }
        }
        private global::System.Int64 _option_id;
        partial void Onoption_idChanging(global::System.Int64 value);
        partial void Onoption_idChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StocksHistoricalDataModel", "FK_option_bids_options", "s_options")]
        public s_options s_options
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<s_options>("StocksHistoricalDataModel.FK_option_bids_options", "s_options").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<s_options>("StocksHistoricalDataModel.FK_option_bids_options", "s_options").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<s_options> s_optionsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<s_options>("StocksHistoricalDataModel.FK_option_bids_options", "s_options");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<s_options>("StocksHistoricalDataModel.FK_option_bids_options", "s_options", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StocksHistoricalDataModel", Name="s_option_closing_prices")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class s_option_closing_prices : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new s_option_closing_prices object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="option_id">Initial value of the option_id property.</param>
        /// <param name="symbol">Initial value of the symbol property.</param>
        /// <param name="timestamp">Initial value of the timestamp property.</param>
        /// <param name="open">Initial value of the open property.</param>
        /// <param name="maximum">Initial value of the maximum property.</param>
        /// <param name="minimum">Initial value of the minimum property.</param>
        public static s_option_closing_prices Creates_option_closing_prices(global::System.Int64 id, global::System.Int64 option_id, global::System.String symbol, global::System.DateTime timestamp, global::System.Decimal open, global::System.Decimal maximum, global::System.Decimal minimum)
        {
            s_option_closing_prices s_option_closing_prices = new s_option_closing_prices();
            s_option_closing_prices.id = id;
            s_option_closing_prices.option_id = option_id;
            s_option_closing_prices.symbol = symbol;
            s_option_closing_prices.timestamp = timestamp;
            s_option_closing_prices.open = open;
            s_option_closing_prices.maximum = maximum;
            s_option_closing_prices.minimum = minimum;
            return s_option_closing_prices;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 option_id
        {
            get
            {
                return _option_id;
            }
            set
            {
                Onoption_idChanging(value);
                ReportPropertyChanging("option_id");
                _option_id = StructuralObject.SetValidValue(value, "option_id");
                ReportPropertyChanged("option_id");
                Onoption_idChanged();
            }
        }
        private global::System.Int64 _option_id;
        partial void Onoption_idChanging(global::System.Int64 value);
        partial void Onoption_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String symbol
        {
            get
            {
                return _symbol;
            }
            set
            {
                OnsymbolChanging(value);
                ReportPropertyChanging("symbol");
                _symbol = StructuralObject.SetValidValue(value, false, "symbol");
                ReportPropertyChanged("symbol");
                OnsymbolChanged();
            }
        }
        private global::System.String _symbol;
        partial void OnsymbolChanging(global::System.String value);
        partial void OnsymbolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime timestamp
        {
            get
            {
                return _timestamp;
            }
            set
            {
                OntimestampChanging(value);
                ReportPropertyChanging("timestamp");
                _timestamp = StructuralObject.SetValidValue(value, "timestamp");
                ReportPropertyChanged("timestamp");
                OntimestampChanged();
            }
        }
        private global::System.DateTime _timestamp;
        partial void OntimestampChanging(global::System.DateTime value);
        partial void OntimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal open
        {
            get
            {
                return _open;
            }
            set
            {
                OnopenChanging(value);
                ReportPropertyChanging("open");
                _open = StructuralObject.SetValidValue(value, "open");
                ReportPropertyChanged("open");
                OnopenChanged();
            }
        }
        private global::System.Decimal _open;
        partial void OnopenChanging(global::System.Decimal value);
        partial void OnopenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal maximum
        {
            get
            {
                return _maximum;
            }
            set
            {
                OnmaximumChanging(value);
                ReportPropertyChanging("maximum");
                _maximum = StructuralObject.SetValidValue(value, "maximum");
                ReportPropertyChanged("maximum");
                OnmaximumChanged();
            }
        }
        private global::System.Decimal _maximum;
        partial void OnmaximumChanging(global::System.Decimal value);
        partial void OnmaximumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal minimum
        {
            get
            {
                return _minimum;
            }
            set
            {
                OnminimumChanging(value);
                ReportPropertyChanging("minimum");
                _minimum = StructuralObject.SetValidValue(value, "minimum");
                ReportPropertyChanged("minimum");
                OnminimumChanged();
            }
        }
        private global::System.Decimal _minimum;
        partial void OnminimumChanging(global::System.Decimal value);
        partial void OnminimumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> close
        {
            get
            {
                return _close;
            }
            set
            {
                OncloseChanging(value);
                ReportPropertyChanging("close");
                _close = StructuralObject.SetValidValue(value, "close");
                ReportPropertyChanged("close");
                OncloseChanged();
            }
        }
        private Nullable<global::System.Decimal> _close;
        partial void OncloseChanging(Nullable<global::System.Decimal> value);
        partial void OncloseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> last_trade
        {
            get
            {
                return _last_trade;
            }
            set
            {
                Onlast_tradeChanging(value);
                ReportPropertyChanging("last_trade");
                _last_trade = StructuralObject.SetValidValue(value, "last_trade");
                ReportPropertyChanged("last_trade");
                Onlast_tradeChanged();
            }
        }
        private Nullable<global::System.Decimal> _last_trade;
        partial void Onlast_tradeChanging(Nullable<global::System.Decimal> value);
        partial void Onlast_tradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> volume
        {
            get
            {
                return _volume;
            }
            set
            {
                OnvolumeChanging(value);
                ReportPropertyChanging("volume");
                _volume = StructuralObject.SetValidValue(value, "volume");
                ReportPropertyChanged("volume");
                OnvolumeChanged();
            }
        }
        private Nullable<global::System.Decimal> _volume;
        partial void OnvolumeChanging(Nullable<global::System.Decimal> value);
        partial void OnvolumeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> open_interest
        {
            get
            {
                return _open_interest;
            }
            set
            {
                Onopen_interestChanging(value);
                ReportPropertyChanging("open_interest");
                _open_interest = StructuralObject.SetValidValue(value, "open_interest");
                ReportPropertyChanged("open_interest");
                Onopen_interestChanged();
            }
        }
        private Nullable<global::System.Decimal> _open_interest;
        partial void Onopen_interestChanging(Nullable<global::System.Decimal> value);
        partial void Onopen_interestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> underlying_price
        {
            get
            {
                return _underlying_price;
            }
            set
            {
                Onunderlying_priceChanging(value);
                ReportPropertyChanging("underlying_price");
                _underlying_price = StructuralObject.SetValidValue(value, "underlying_price");
                ReportPropertyChanged("underlying_price");
                Onunderlying_priceChanged();
            }
        }
        private Nullable<global::System.Decimal> _underlying_price;
        partial void Onunderlying_priceChanging(Nullable<global::System.Decimal> value);
        partial void Onunderlying_priceChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StocksHistoricalDataModel", "FK_option_closing_prices_options", "s_options")]
        public s_options s_options
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<s_options>("StocksHistoricalDataModel.FK_option_closing_prices_options", "s_options").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<s_options>("StocksHistoricalDataModel.FK_option_closing_prices_options", "s_options").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<s_options> s_optionsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<s_options>("StocksHistoricalDataModel.FK_option_closing_prices_options", "s_options");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<s_options>("StocksHistoricalDataModel.FK_option_closing_prices_options", "s_options", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StocksHistoricalDataModel", Name="s_options")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class s_options : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new s_options object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="symbol">Initial value of the symbol property.</param>
        /// <param name="symbol_sfx">Initial value of the symbol_sfx property.</param>
        /// <param name="strike_multiplier">Initial value of the strike_multiplier property.</param>
        /// <param name="put_or_call">Initial value of the put_or_call property.</param>
        /// <param name="strike_price">Initial value of the strike_price property.</param>
        /// <param name="strike_currency">Initial value of the strike_currency property.</param>
        /// <param name="maturity_month_year">Initial value of the maturity_month_year property.</param>
        /// <param name="maturity_date">Initial value of the maturity_date property.</param>
        /// <param name="expired">Initial value of the expired property.</param>
        public static s_options Creates_options(global::System.Int64 id, global::System.String symbol, global::System.String symbol_sfx, global::System.Int32 strike_multiplier, global::System.String put_or_call, global::System.Decimal strike_price, global::System.String strike_currency, global::System.String maturity_month_year, global::System.DateTime maturity_date, global::System.Boolean expired)
        {
            s_options s_options = new s_options();
            s_options.id = id;
            s_options.symbol = symbol;
            s_options.symbol_sfx = symbol_sfx;
            s_options.strike_multiplier = strike_multiplier;
            s_options.put_or_call = put_or_call;
            s_options.strike_price = strike_price;
            s_options.strike_currency = strike_currency;
            s_options.maturity_month_year = maturity_month_year;
            s_options.maturity_date = maturity_date;
            s_options.expired = expired;
            return s_options;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String symbol
        {
            get
            {
                return _symbol;
            }
            set
            {
                OnsymbolChanging(value);
                ReportPropertyChanging("symbol");
                _symbol = StructuralObject.SetValidValue(value, false, "symbol");
                ReportPropertyChanged("symbol");
                OnsymbolChanged();
            }
        }
        private global::System.String _symbol;
        partial void OnsymbolChanging(global::System.String value);
        partial void OnsymbolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String symbol_sfx
        {
            get
            {
                return _symbol_sfx;
            }
            set
            {
                Onsymbol_sfxChanging(value);
                ReportPropertyChanging("symbol_sfx");
                _symbol_sfx = StructuralObject.SetValidValue(value, false, "symbol_sfx");
                ReportPropertyChanged("symbol_sfx");
                Onsymbol_sfxChanged();
            }
        }
        private global::System.String _symbol_sfx;
        partial void Onsymbol_sfxChanging(global::System.String value);
        partial void Onsymbol_sfxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 strike_multiplier
        {
            get
            {
                return _strike_multiplier;
            }
            set
            {
                Onstrike_multiplierChanging(value);
                ReportPropertyChanging("strike_multiplier");
                _strike_multiplier = StructuralObject.SetValidValue(value, "strike_multiplier");
                ReportPropertyChanged("strike_multiplier");
                Onstrike_multiplierChanged();
            }
        }
        private global::System.Int32 _strike_multiplier;
        partial void Onstrike_multiplierChanging(global::System.Int32 value);
        partial void Onstrike_multiplierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String put_or_call
        {
            get
            {
                return _put_or_call;
            }
            set
            {
                Onput_or_callChanging(value);
                ReportPropertyChanging("put_or_call");
                _put_or_call = StructuralObject.SetValidValue(value, false, "put_or_call");
                ReportPropertyChanged("put_or_call");
                Onput_or_callChanged();
            }
        }
        private global::System.String _put_or_call;
        partial void Onput_or_callChanging(global::System.String value);
        partial void Onput_or_callChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal strike_price
        {
            get
            {
                return _strike_price;
            }
            set
            {
                Onstrike_priceChanging(value);
                ReportPropertyChanging("strike_price");
                _strike_price = StructuralObject.SetValidValue(value, "strike_price");
                ReportPropertyChanged("strike_price");
                Onstrike_priceChanged();
            }
        }
        private global::System.Decimal _strike_price;
        partial void Onstrike_priceChanging(global::System.Decimal value);
        partial void Onstrike_priceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strike_currency
        {
            get
            {
                return _strike_currency;
            }
            set
            {
                Onstrike_currencyChanging(value);
                ReportPropertyChanging("strike_currency");
                _strike_currency = StructuralObject.SetValidValue(value, false, "strike_currency");
                ReportPropertyChanged("strike_currency");
                Onstrike_currencyChanged();
            }
        }
        private global::System.String _strike_currency;
        partial void Onstrike_currencyChanging(global::System.String value);
        partial void Onstrike_currencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String maturity_month_year
        {
            get
            {
                return _maturity_month_year;
            }
            set
            {
                Onmaturity_month_yearChanging(value);
                ReportPropertyChanging("maturity_month_year");
                _maturity_month_year = StructuralObject.SetValidValue(value, false, "maturity_month_year");
                ReportPropertyChanged("maturity_month_year");
                Onmaturity_month_yearChanged();
            }
        }
        private global::System.String _maturity_month_year;
        partial void Onmaturity_month_yearChanging(global::System.String value);
        partial void Onmaturity_month_yearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime maturity_date
        {
            get
            {
                return _maturity_date;
            }
            set
            {
                Onmaturity_dateChanging(value);
                ReportPropertyChanging("maturity_date");
                _maturity_date = StructuralObject.SetValidValue(value, "maturity_date");
                ReportPropertyChanged("maturity_date");
                Onmaturity_dateChanged();
            }
        }
        private global::System.DateTime _maturity_date;
        partial void Onmaturity_dateChanging(global::System.DateTime value);
        partial void Onmaturity_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String currency
        {
            get
            {
                return _currency;
            }
            set
            {
                OncurrencyChanging(value);
                ReportPropertyChanging("currency");
                _currency = StructuralObject.SetValidValue(value, true, "currency");
                ReportPropertyChanged("currency");
                OncurrencyChanged();
            }
        }
        private global::System.String _currency;
        partial void OncurrencyChanging(global::System.String value);
        partial void OncurrencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String security_exchange
        {
            get
            {
                return _security_exchange;
            }
            set
            {
                Onsecurity_exchangeChanging(value);
                ReportPropertyChanging("security_exchange");
                _security_exchange = StructuralObject.SetValidValue(value, true, "security_exchange");
                ReportPropertyChanged("security_exchange");
                Onsecurity_exchangeChanged();
            }
        }
        private global::System.String _security_exchange;
        partial void Onsecurity_exchangeChanging(global::System.String value);
        partial void Onsecurity_exchangeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean expired
        {
            get
            {
                return _expired;
            }
            set
            {
                OnexpiredChanging(value);
                ReportPropertyChanging("expired");
                _expired = StructuralObject.SetValidValue(value, "expired");
                ReportPropertyChanged("expired");
                OnexpiredChanged();
            }
        }
        private global::System.Boolean _expired;
        partial void OnexpiredChanging(global::System.Boolean value);
        partial void OnexpiredChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StocksHistoricalDataModel", "FK_option_bids_options", "s_option_bids")]
        public EntityCollection<s_option_bids> s_option_bids
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<s_option_bids>("StocksHistoricalDataModel.FK_option_bids_options", "s_option_bids");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<s_option_bids>("StocksHistoricalDataModel.FK_option_bids_options", "s_option_bids", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StocksHistoricalDataModel", "FK_option_closing_prices_options", "s_option_closing_prices")]
        public EntityCollection<s_option_closing_prices> s_option_closing_prices
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<s_option_closing_prices>("StocksHistoricalDataModel.FK_option_closing_prices_options", "s_option_closing_prices");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<s_option_closing_prices>("StocksHistoricalDataModel.FK_option_closing_prices_options", "s_option_closing_prices", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StocksHistoricalDataModel", Name="s_stocks")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class s_stocks : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new s_stocks object.
        /// </summary>
        /// <param name="codigo_especie">Initial value of the codigo_especie property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        public static s_stocks Creates_stocks(global::System.String codigo_especie, global::System.String nombre)
        {
            s_stocks s_stocks = new s_stocks();
            s_stocks.codigo_especie = codigo_especie;
            s_stocks.nombre = nombre;
            return s_stocks;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo_especie
        {
            get
            {
                return _codigo_especie;
            }
            set
            {
                if (_codigo_especie != value)
                {
                    Oncodigo_especieChanging(value);
                    ReportPropertyChanging("codigo_especie");
                    _codigo_especie = StructuralObject.SetValidValue(value, false, "codigo_especie");
                    ReportPropertyChanged("codigo_especie");
                    Oncodigo_especieChanged();
                }
            }
        }
        private global::System.String _codigo_especie;
        partial void Oncodigo_especieChanging(global::System.String value);
        partial void Oncodigo_especieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false, "nombre");
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mercado
        {
            get
            {
                return _mercado;
            }
            set
            {
                OnmercadoChanging(value);
                ReportPropertyChanging("mercado");
                _mercado = StructuralObject.SetValidValue(value, true, "mercado");
                ReportPropertyChanged("mercado");
                OnmercadoChanged();
            }
        }
        private global::System.String _mercado;
        partial void OnmercadoChanging(global::System.String value);
        partial void OnmercadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pais
        {
            get
            {
                return _pais;
            }
            set
            {
                OnpaisChanging(value);
                ReportPropertyChanging("pais");
                _pais = StructuralObject.SetValidValue(value, true, "pais");
                ReportPropertyChanged("pais");
                OnpaisChanged();
            }
        }
        private global::System.String _pais;
        partial void OnpaisChanging(global::System.String value);
        partial void OnpaisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String categoria
        {
            get
            {
                return _categoria;
            }
            set
            {
                OncategoriaChanging(value);
                ReportPropertyChanging("categoria");
                _categoria = StructuralObject.SetValidValue(value, true, "categoria");
                ReportPropertyChanged("categoria");
                OncategoriaChanged();
            }
        }
        private global::System.String _categoria;
        partial void OncategoriaChanging(global::System.String value);
        partial void OncategoriaChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StocksHistoricalDataModel", Name="stocks_market_data")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class stocks_market_data : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new stocks_market_data object.
        /// </summary>
        /// <param name="symbol">Initial value of the symbol property.</param>
        /// <param name="date">Initial value of the date property.</param>
        public static stocks_market_data Createstocks_market_data(global::System.String symbol, global::System.DateTime date)
        {
            stocks_market_data stocks_market_data = new stocks_market_data();
            stocks_market_data.symbol = symbol;
            stocks_market_data.date = date;
            return stocks_market_data;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String symbol
        {
            get
            {
                return _symbol;
            }
            set
            {
                if (_symbol != value)
                {
                    OnsymbolChanging(value);
                    ReportPropertyChanging("symbol");
                    _symbol = StructuralObject.SetValidValue(value, false, "symbol");
                    ReportPropertyChanged("symbol");
                    OnsymbolChanged();
                }
            }
        }
        private global::System.String _symbol;
        partial void OnsymbolChanging(global::System.String value);
        partial void OnsymbolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                if (_date != value)
                {
                    OndateChanging(value);
                    ReportPropertyChanging("date");
                    _date = StructuralObject.SetValidValue(value, "date");
                    ReportPropertyChanged("date");
                    OndateChanged();
                }
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> apertura
        {
            get
            {
                return _apertura;
            }
            set
            {
                OnaperturaChanging(value);
                ReportPropertyChanging("apertura");
                _apertura = StructuralObject.SetValidValue(value, "apertura");
                ReportPropertyChanged("apertura");
                OnaperturaChanged();
            }
        }
        private Nullable<global::System.Double> _apertura;
        partial void OnaperturaChanging(Nullable<global::System.Double> value);
        partial void OnaperturaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> maximo
        {
            get
            {
                return _maximo;
            }
            set
            {
                OnmaximoChanging(value);
                ReportPropertyChanging("maximo");
                _maximo = StructuralObject.SetValidValue(value, "maximo");
                ReportPropertyChanged("maximo");
                OnmaximoChanged();
            }
        }
        private Nullable<global::System.Double> _maximo;
        partial void OnmaximoChanging(Nullable<global::System.Double> value);
        partial void OnmaximoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> minimo
        {
            get
            {
                return _minimo;
            }
            set
            {
                OnminimoChanging(value);
                ReportPropertyChanging("minimo");
                _minimo = StructuralObject.SetValidValue(value, "minimo");
                ReportPropertyChanged("minimo");
                OnminimoChanged();
            }
        }
        private Nullable<global::System.Double> _minimo;
        partial void OnminimoChanging(Nullable<global::System.Double> value);
        partial void OnminimoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> cierre
        {
            get
            {
                return _cierre;
            }
            set
            {
                OncierreChanging(value);
                ReportPropertyChanging("cierre");
                _cierre = StructuralObject.SetValidValue(value, "cierre");
                ReportPropertyChanged("cierre");
                OncierreChanged();
            }
        }
        private Nullable<global::System.Double> _cierre;
        partial void OncierreChanging(Nullable<global::System.Double> value);
        partial void OncierreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> volumen_nominal
        {
            get
            {
                return _volumen_nominal;
            }
            set
            {
                Onvolumen_nominalChanging(value);
                ReportPropertyChanging("volumen_nominal");
                _volumen_nominal = StructuralObject.SetValidValue(value, "volumen_nominal");
                ReportPropertyChanged("volumen_nominal");
                Onvolumen_nominalChanged();
            }
        }
        private Nullable<global::System.Double> _volumen_nominal;
        partial void Onvolumen_nominalChanging(Nullable<global::System.Double> value);
        partial void Onvolumen_nominalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> volumen_monetario
        {
            get
            {
                return _volumen_monetario;
            }
            set
            {
                Onvolumen_monetarioChanging(value);
                ReportPropertyChanging("volumen_monetario");
                _volumen_monetario = StructuralObject.SetValidValue(value, "volumen_monetario");
                ReportPropertyChanged("volumen_monetario");
                Onvolumen_monetarioChanged();
            }
        }
        private Nullable<global::System.Double> _volumen_monetario;
        partial void Onvolumen_monetarioChanging(Nullable<global::System.Double> value);
        partial void Onvolumen_monetarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> precio_ultima_operacion
        {
            get
            {
                return _precio_ultima_operacion;
            }
            set
            {
                Onprecio_ultima_operacionChanging(value);
                ReportPropertyChanging("precio_ultima_operacion");
                _precio_ultima_operacion = StructuralObject.SetValidValue(value, "precio_ultima_operacion");
                ReportPropertyChanged("precio_ultima_operacion");
                Onprecio_ultima_operacionChanged();
            }
        }
        private Nullable<global::System.Double> _precio_ultima_operacion;
        partial void Onprecio_ultima_operacionChanging(Nullable<global::System.Double> value);
        partial void Onprecio_ultima_operacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> volumen_ultima_operacion
        {
            get
            {
                return _volumen_ultima_operacion;
            }
            set
            {
                Onvolumen_ultima_operacionChanging(value);
                ReportPropertyChanging("volumen_ultima_operacion");
                _volumen_ultima_operacion = StructuralObject.SetValidValue(value, "volumen_ultima_operacion");
                ReportPropertyChanged("volumen_ultima_operacion");
                Onvolumen_ultima_operacionChanged();
            }
        }
        private Nullable<global::System.Double> _volumen_ultima_operacion;
        partial void Onvolumen_ultima_operacionChanging(Nullable<global::System.Double> value);
        partial void Onvolumen_ultima_operacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> mejor_bid_precio
        {
            get
            {
                return _mejor_bid_precio;
            }
            set
            {
                Onmejor_bid_precioChanging(value);
                ReportPropertyChanging("mejor_bid_precio");
                _mejor_bid_precio = StructuralObject.SetValidValue(value, "mejor_bid_precio");
                ReportPropertyChanged("mejor_bid_precio");
                Onmejor_bid_precioChanged();
            }
        }
        private Nullable<global::System.Double> _mejor_bid_precio;
        partial void Onmejor_bid_precioChanging(Nullable<global::System.Double> value);
        partial void Onmejor_bid_precioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> mejor_bid_tamano
        {
            get
            {
                return _mejor_bid_tamano;
            }
            set
            {
                Onmejor_bid_tamanoChanging(value);
                ReportPropertyChanging("mejor_bid_tamano");
                _mejor_bid_tamano = StructuralObject.SetValidValue(value, "mejor_bid_tamano");
                ReportPropertyChanged("mejor_bid_tamano");
                Onmejor_bid_tamanoChanged();
            }
        }
        private Nullable<global::System.Int64> _mejor_bid_tamano;
        partial void Onmejor_bid_tamanoChanging(Nullable<global::System.Int64> value);
        partial void Onmejor_bid_tamanoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mejor_bid_exch
        {
            get
            {
                return _mejor_bid_exch;
            }
            set
            {
                Onmejor_bid_exchChanging(value);
                ReportPropertyChanging("mejor_bid_exch");
                _mejor_bid_exch = StructuralObject.SetValidValue(value, true, "mejor_bid_exch");
                ReportPropertyChanged("mejor_bid_exch");
                Onmejor_bid_exchChanged();
            }
        }
        private global::System.String _mejor_bid_exch;
        partial void Onmejor_bid_exchChanging(global::System.String value);
        partial void Onmejor_bid_exchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> mejor_ask_precio
        {
            get
            {
                return _mejor_ask_precio;
            }
            set
            {
                Onmejor_ask_precioChanging(value);
                ReportPropertyChanging("mejor_ask_precio");
                _mejor_ask_precio = StructuralObject.SetValidValue(value, "mejor_ask_precio");
                ReportPropertyChanged("mejor_ask_precio");
                Onmejor_ask_precioChanged();
            }
        }
        private Nullable<global::System.Double> _mejor_ask_precio;
        partial void Onmejor_ask_precioChanging(Nullable<global::System.Double> value);
        partial void Onmejor_ask_precioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> mejor_ask_tamano
        {
            get
            {
                return _mejor_ask_tamano;
            }
            set
            {
                Onmejor_ask_tamanoChanging(value);
                ReportPropertyChanging("mejor_ask_tamano");
                _mejor_ask_tamano = StructuralObject.SetValidValue(value, "mejor_ask_tamano");
                ReportPropertyChanged("mejor_ask_tamano");
                Onmejor_ask_tamanoChanged();
            }
        }
        private Nullable<global::System.Int64> _mejor_ask_tamano;
        partial void Onmejor_ask_tamanoChanging(Nullable<global::System.Int64> value);
        partial void Onmejor_ask_tamanoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mejor_ask_exch
        {
            get
            {
                return _mejor_ask_exch;
            }
            set
            {
                Onmejor_ask_exchChanging(value);
                ReportPropertyChanging("mejor_ask_exch");
                _mejor_ask_exch = StructuralObject.SetValidValue(value, true, "mejor_ask_exch");
                ReportPropertyChanged("mejor_ask_exch");
                Onmejor_ask_exchChanged();
            }
        }
        private global::System.String _mejor_ask_exch;
        partial void Onmejor_ask_exchChanging(global::System.String value);
        partial void Onmejor_ask_exchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String moneda
        {
            get
            {
                return _moneda;
            }
            set
            {
                OnmonedaChanging(value);
                ReportPropertyChanging("moneda");
                _moneda = StructuralObject.SetValidValue(value, true, "moneda");
                ReportPropertyChanged("moneda");
                OnmonedaChanged();
            }
        }
        private global::System.String _moneda;
        partial void OnmonedaChanging(global::System.String value);
        partial void OnmonedaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sesion
        {
            get
            {
                return _sesion;
            }
            set
            {
                OnsesionChanging(value);
                ReportPropertyChanging("sesion");
                _sesion = StructuralObject.SetValidValue(value, true, "sesion");
                ReportPropertyChanged("sesion");
                OnsesionChanged();
            }
        }
        private global::System.String _sesion;
        partial void OnsesionChanging(global::System.String value);
        partial void OnsesionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> timestamp
        {
            get
            {
                return _timestamp;
            }
            set
            {
                OntimestampChanging(value);
                ReportPropertyChanging("timestamp");
                _timestamp = StructuralObject.SetValidValue(value, "timestamp");
                ReportPropertyChanged("timestamp");
                OntimestampChanged();
            }
        }
        private Nullable<global::System.DateTime> _timestamp;
        partial void OntimestampChanging(Nullable<global::System.DateTime> value);
        partial void OntimestampChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StocksHistoricalDataModel", Name="stocks_prices")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class stocks_prices : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new stocks_prices object.
        /// </summary>
        /// <param name="codigo_especie">Initial value of the codigo_especie property.</param>
        /// <param name="fecha">Initial value of the fecha property.</param>
        /// <param name="apertura">Initial value of the apertura property.</param>
        /// <param name="maximo">Initial value of the maximo property.</param>
        /// <param name="minimo">Initial value of the minimo property.</param>
        /// <param name="cierre">Initial value of the cierre property.</param>
        /// <param name="volumen">Initial value of the volumen property.</param>
        /// <param name="adj_cierre">Initial value of the adj_cierre property.</param>
        public static stocks_prices Createstocks_prices(global::System.String codigo_especie, global::System.DateTime fecha, global::System.Decimal apertura, global::System.Decimal maximo, global::System.Decimal minimo, global::System.Decimal cierre, global::System.Int64 volumen, global::System.Decimal adj_cierre)
        {
            stocks_prices stocks_prices = new stocks_prices();
            stocks_prices.codigo_especie = codigo_especie;
            stocks_prices.fecha = fecha;
            stocks_prices.apertura = apertura;
            stocks_prices.maximo = maximo;
            stocks_prices.minimo = minimo;
            stocks_prices.cierre = cierre;
            stocks_prices.volumen = volumen;
            stocks_prices.adj_cierre = adj_cierre;
            return stocks_prices;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo_especie
        {
            get
            {
                return _codigo_especie;
            }
            set
            {
                if (_codigo_especie != value)
                {
                    Oncodigo_especieChanging(value);
                    ReportPropertyChanging("codigo_especie");
                    _codigo_especie = StructuralObject.SetValidValue(value, false, "codigo_especie");
                    ReportPropertyChanged("codigo_especie");
                    Oncodigo_especieChanged();
                }
            }
        }
        private global::System.String _codigo_especie;
        partial void Oncodigo_especieChanging(global::System.String value);
        partial void Oncodigo_especieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                if (_fecha != value)
                {
                    OnfechaChanging(value);
                    ReportPropertyChanging("fecha");
                    _fecha = StructuralObject.SetValidValue(value, "fecha");
                    ReportPropertyChanged("fecha");
                    OnfechaChanged();
                }
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal apertura
        {
            get
            {
                return _apertura;
            }
            set
            {
                OnaperturaChanging(value);
                ReportPropertyChanging("apertura");
                _apertura = StructuralObject.SetValidValue(value, "apertura");
                ReportPropertyChanged("apertura");
                OnaperturaChanged();
            }
        }
        private global::System.Decimal _apertura;
        partial void OnaperturaChanging(global::System.Decimal value);
        partial void OnaperturaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal maximo
        {
            get
            {
                return _maximo;
            }
            set
            {
                OnmaximoChanging(value);
                ReportPropertyChanging("maximo");
                _maximo = StructuralObject.SetValidValue(value, "maximo");
                ReportPropertyChanged("maximo");
                OnmaximoChanged();
            }
        }
        private global::System.Decimal _maximo;
        partial void OnmaximoChanging(global::System.Decimal value);
        partial void OnmaximoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal minimo
        {
            get
            {
                return _minimo;
            }
            set
            {
                OnminimoChanging(value);
                ReportPropertyChanging("minimo");
                _minimo = StructuralObject.SetValidValue(value, "minimo");
                ReportPropertyChanged("minimo");
                OnminimoChanged();
            }
        }
        private global::System.Decimal _minimo;
        partial void OnminimoChanging(global::System.Decimal value);
        partial void OnminimoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cierre
        {
            get
            {
                return _cierre;
            }
            set
            {
                OncierreChanging(value);
                ReportPropertyChanging("cierre");
                _cierre = StructuralObject.SetValidValue(value, "cierre");
                ReportPropertyChanged("cierre");
                OncierreChanged();
            }
        }
        private global::System.Decimal _cierre;
        partial void OncierreChanging(global::System.Decimal value);
        partial void OncierreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 volumen
        {
            get
            {
                return _volumen;
            }
            set
            {
                OnvolumenChanging(value);
                ReportPropertyChanging("volumen");
                _volumen = StructuralObject.SetValidValue(value, "volumen");
                ReportPropertyChanged("volumen");
                OnvolumenChanged();
            }
        }
        private global::System.Int64 _volumen;
        partial void OnvolumenChanging(global::System.Int64 value);
        partial void OnvolumenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal adj_cierre
        {
            get
            {
                return _adj_cierre;
            }
            set
            {
                Onadj_cierreChanging(value);
                ReportPropertyChanging("adj_cierre");
                _adj_cierre = StructuralObject.SetValidValue(value, "adj_cierre");
                ReportPropertyChanged("adj_cierre");
                Onadj_cierreChanged();
            }
        }
        private global::System.Decimal _adj_cierre;
        partial void Onadj_cierreChanging(global::System.Decimal value);
        partial void Onadj_cierreChanged();

        #endregion

    }

    #endregion

}
